apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: rhdhpai802-final2
  janus-idp.io/tekton: rhdhpai802-final2
  backstage.io/kubernetes-id: rhdhpai802-final2
  backstage.io/kubernetes-namespace: rhdhpai802-final2
  app.kubernetes.io/part-of: rhdhpai802-final2
resources:
  - initialize-namespace/
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
