apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-dsp-rhdhpai802-final2-gitops
spec:
  template:
    metadata:
      name: initialize-dsp-rhdhpai802-final2-gitops
    spec:
      serviceAccountName: rhdhpai802-final2-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              # Wait for the Image Stream creation job to finish
              echo "Wait for the Image Stream job"
              oc wait --for=condition=complete job/create-imagestream-rhdhpai802-final2-gitops
              echo "Done"

              # Wait for the Namespace initialize job to finish
              echo "Wait for the Namespace job"
              oc wait --for=condition=complete job/initialize-namespace-rhdhpai802-final2-gitops
              echo "Done"

              # Label the namespace as a DataScienceProject
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc label ns $NS opendatahub.io/dashboard=true --overwrite

              # Retrieve the UID for the notebook SA, and mark the notebook as owned by it for garbage collection purposes
              SA_UID=$(oc get sa rhdhpai802-final2-dsp-job -o json | jq -r .metadata.uid)
              echo "$SA_UID"
              cat <<EOF | oc apply -f -
              apiVersion: kubeflow.org/v1
              kind: Notebook
              metadata:
                annotations:
                  notebooks.opendatahub.io/inject-oauth: 'true'
                  opendatahub.io/image-display-name: Minimal Python
                  opendatahub.io/accelerator-name: ''
                  openshift.io/description: ''
                  openshift.io/display-name: rhdhpai802-final2-notebook
                  notebooks.opendatahub.io/last-image-selection: 's2i-minimal-notebook:2024.1'
                  notebooks.opendatahub.io/last-size-selection: Small
                name: rhdhpai802-final2-notebook
                namespace: rhdhpai802-final2
                ownerReferences:
                  - apiVersion: v1
                    kind: ServiceAccount
                    name: rhdhpai802-final2-dsp-job
                    uid: $SA_UID
                labels:
                  app: rhdhpai802-final2-notebook
                  opendatahub.io/dashboard: 'true'
                  opendatahub.io/odh-managed: 'true'
              spec:
                template:
                  spec:
                    affinity: {}
                    containers:
                      - resources:
                          limits:
                            cpu: '2'
                            memory: 8Gi
                          requests:
                            cpu: '1'
                            memory: 8Gi
                        readinessProbe:
                          failureThreshold: 3
                          httpGet:
                            path: '/notebook/rhdhpai802-final2/rhdhpai802-final2-notebook/api'
                            port: notebook-port
                            scheme: HTTP
                          initialDelaySeconds: 10
                          periodSeconds: 5
                          successThreshold: 1
                          timeoutSeconds: 1
                        name: rhdhpai802-final2-notebook
                        livenessProbe:
                          failureThreshold: 3
                          httpGet:
                            path: '/notebook/rhdhpai802-final2/rhdhpai802-final2-notebook/api'
                            port: notebook-port
                            scheme: HTTP
                          initialDelaySeconds: 10
                          periodSeconds: 5
                          successThreshold: 1
                          timeoutSeconds: 1
                        env:
                          - name: NOTEBOOK_ARGS
                            value: |-
                              --ServerApp.port=8888
                                                --ServerApp.token=''
                                                --ServerApp.password=''
                                                --ServerApp.base_url=/notebook/rhdhpai802-final2/rhdhpai802-final2-notebook
                                                --ServerApp.quit_button=False
                          - name: JUPYTER_IMAGE
                            value: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/custom-sqlite3-odh-minimal-notebook-container:v2-2024a-20240523-sqlite3'
                        envFrom:
                        - configMapRef:
                            name: rhdhpai802-final2-model-config
                        ports:
                          - containerPort: 8888
                            name: notebook-port
                            protocol: TCP
                        imagePullPolicy: Always
                        volumeMounts:
                          - mountPath: /opt/app-root/src
                            name: rhdhpai802-final2-notebook
                          - mountPath: /dev/shm
                            name: shm
                        image: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/custom-sqlite3-odh-minimal-notebook-container:v2-2024a-20240523-sqlite3'
                        workingDir: /opt/app-root/src
                    enableServiceLinks: false
                    serviceAccountName: rhdhpai802-final2-notebook
                    volumes:
                      - name: rhdhpai802-final2-notebook
                        persistentVolumeClaim:
                          claimName: rhdhpai802-final2-notebook-rhoai
                      - emptyDir:
                          medium: Memory
                        name: shm
              ---
              kind: PersistentVolumeClaim
              apiVersion: v1
              metadata:
                annotations:
                  openshift.io/display-name: rhdhpai802-final2-notebook-rhoai
                name: rhdhpai802-final2-notebook-rhoai
                ownerReferences:
                  - apiVersion: v1
                    kind: ServiceAccount
                    name: rhdhpai802-final2-dsp-job
                    uid: $SA_UID
                labels:
                  opendatahub.io/dashboard: 'true'
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 20Gi
                volumeMode: Filesystem
              EOF
      restartPolicy: Never
